
// generated by cap at 2022-12-22 10:31:02.3008083 +0800 CST m=+0.011113501, DO NOT EDIT.
package errors

import (
	"fmt"

	"github.com/XShareGrid/cap/msg/i18n"
	"golang.org/x/text/language"
)

var errors_lr errors_langRegistry

func initTrRegistry() {
	if errors_lr == nil {
		errors_lr = errors_langRegistry{}
	}
}

func (l errors_langRegistry) addTranslation(id i18n.TrID, lang language.Tag, translation string) error {
	if ts, ok := errors_lr[id]; ok {
		if _, ok := ts[lang]; ok {
			return fmt.Errorf("duplicate translation for [%s#%s]", id, lang.String())
		}
		l[id][lang] = translation
	} else {
		l[id] = map[language.Tag]string{
			lang: translation,
		}
	}
	return nil
}

func init() {
	i18n.AddTrCandidates(&errors_tr{})
}

// map[langID]map[langCode]translation
type errors_langRegistry map[i18n.TrID]map[language.Tag]string

type errors_tr struct {
}

func (t *errors_tr) Translate(lang language.Tag, id i18n.TrID, args ...interface{}) (string, error) {
	if ts, ok := errors_lr[id]; ok {
		if t, ok := ts[lang]; ok {
			return fmt.Sprintf(t, args...), nil
		}
	}
	return "", i18n.ErrNoTranslateCandidate
}
