// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: table_wservice.proto

package cap

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TableWService_GetTableInfo_FullMethodName          = "/cap.TableWService/GetTableInfo"
	TableWService_GetTableTemplates_FullMethodName     = "/cap.TableWService/GetTableTemplates"
	TableWService_CreateTableTemplate_FullMethodName   = "/cap.TableWService/CreateTableTemplate"
	TableWService_DeleteTableTemplate_FullMethodName   = "/cap.TableWService/DeleteTableTemplate"
	TableWService_UpdateTableTemplate_FullMethodName   = "/cap.TableWService/UpdateTableTemplate"
	TableWService_GetTableColumns_FullMethodName       = "/cap.TableWService/GetTableColumns"
	TableWService_GetTableRows_FullMethodName          = "/cap.TableWService/GetTableRows"
	TableWService_GetTableRowByID_FullMethodName       = "/cap.TableWService/GetTableRowByID"
	TableWService_DoExportTable_FullMethodName         = "/cap.TableWService/DoExportTable"
	TableWService_GetTableColumnOptions_FullMethodName = "/cap.TableWService/GetTableColumnOptions"
	TableWService_GetTableRowsLite_FullMethodName      = "/cap.TableWService/GetTableRowsLite"
	TableWService_GetOptions_FullMethodName            = "/cap.TableWService/GetOptions"
	TableWService_DoRowFormAction_FullMethodName       = "/cap.TableWService/DoRowFormAction"
	TableWService_DeleteRows_FullMethodName            = "/cap.TableWService/DeleteRows"
)

// TableWServiceClient is the client API for TableWService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TableWService 表格服务
// 每个子系统都可能提供该服务 /cap.TableWService，并统一通过EAP的端口暴露
// 前端可使用http header["Subsystem"]或者["Referer"]来指定子系统
// 例如访问[mts]下的表格服务，可以如下设置：
//
//	示例1: HTTP Header["Subsystem"] = "/mts"
//	示例2: HTTP Header["Referer"] = "/mts/...."
//
// 注意：上线系统中referer由浏览器自动设置，无需手动设置，调试时可使用Subsystem
// Header
type TableWServiceClient interface {
	// 表
	// GetTableInfo 获取表信息
	GetTableInfo(ctx context.Context, in *GetTableInfoReq, opts ...grpc.CallOption) (*CommonRsp, error)
	// 模板
	// GetTableTemplates 获取表模板信息
	GetTableTemplates(ctx context.Context, in *GetTableTemplatesReq, opts ...grpc.CallOption) (*CommonRsp, error)
	// CreateTableTemplate 创建模板
	CreateTableTemplate(ctx context.Context, in *CreateTableTemplateReq, opts ...grpc.CallOption) (*CommonRsp, error)
	// DeleteTableTemplate 删除模板
	DeleteTableTemplate(ctx context.Context, in *DeleteTableTemplateReq, opts ...grpc.CallOption) (*CommonRsp, error)
	// UpdateTableTemplate 更新模板
	UpdateTableTemplate(ctx context.Context, in *CreateTableTemplateReq, opts ...grpc.CallOption) (*CommonRsp, error)
	// 数据
	// GetTableColumns 获取表列
	GetTableColumns(ctx context.Context, in *GetTableColumnsReq, opts ...grpc.CallOption) (*CommonRsp, error)
	// GetTableRows 获取表行
	GetTableRows(ctx context.Context, in *GetTableRowsReq, opts ...grpc.CallOption) (*CommonRsp, error)
	// GetTableRowByID 精确获取一行
	GetTableRowByID(ctx context.Context, in *GetTableRowByIDReq, opts ...grpc.CallOption) (*CommonRsp, error)
	// DoExportTable 导出表
	DoExportTable(ctx context.Context, in *GetTableRowsReq, opts ...grpc.CallOption) (*CommonRsp, error)
	// GetTableColumnOptions 获取列选项列表（仅ValueType = VT_OPTION时可获取）
	GetTableColumnOptions(ctx context.Context, in *GetTableColumnOptionsReq, opts ...grpc.CallOption) (*CommonRsp, error)
	// GetTableRowsLite 简单版获取行列表接口
	GetTableRowsLite(ctx context.Context, in *GetTableRowsLiteReq, opts ...grpc.CallOption) (*CommonRsp, error)
	// GetOptions 根据Option ID获取
	GetOptions(ctx context.Context, in *GetOptionsReq, opts ...grpc.CallOption) (*CommonRsp, error)
	// 执行表单操作
	DoRowFormAction(ctx context.Context, in *DoRowFormActionReq, opts ...grpc.CallOption) (*CommonRsp, error)
	// 执行表单操作
	DeleteRows(ctx context.Context, in *DeleteRowsReq, opts ...grpc.CallOption) (*CommonRsp, error)
}

type tableWServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTableWServiceClient(cc grpc.ClientConnInterface) TableWServiceClient {
	return &tableWServiceClient{cc}
}

func (c *tableWServiceClient) GetTableInfo(ctx context.Context, in *GetTableInfoReq, opts ...grpc.CallOption) (*CommonRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonRsp)
	err := c.cc.Invoke(ctx, TableWService_GetTableInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableWServiceClient) GetTableTemplates(ctx context.Context, in *GetTableTemplatesReq, opts ...grpc.CallOption) (*CommonRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonRsp)
	err := c.cc.Invoke(ctx, TableWService_GetTableTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableWServiceClient) CreateTableTemplate(ctx context.Context, in *CreateTableTemplateReq, opts ...grpc.CallOption) (*CommonRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonRsp)
	err := c.cc.Invoke(ctx, TableWService_CreateTableTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableWServiceClient) DeleteTableTemplate(ctx context.Context, in *DeleteTableTemplateReq, opts ...grpc.CallOption) (*CommonRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonRsp)
	err := c.cc.Invoke(ctx, TableWService_DeleteTableTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableWServiceClient) UpdateTableTemplate(ctx context.Context, in *CreateTableTemplateReq, opts ...grpc.CallOption) (*CommonRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonRsp)
	err := c.cc.Invoke(ctx, TableWService_UpdateTableTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableWServiceClient) GetTableColumns(ctx context.Context, in *GetTableColumnsReq, opts ...grpc.CallOption) (*CommonRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonRsp)
	err := c.cc.Invoke(ctx, TableWService_GetTableColumns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableWServiceClient) GetTableRows(ctx context.Context, in *GetTableRowsReq, opts ...grpc.CallOption) (*CommonRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonRsp)
	err := c.cc.Invoke(ctx, TableWService_GetTableRows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableWServiceClient) GetTableRowByID(ctx context.Context, in *GetTableRowByIDReq, opts ...grpc.CallOption) (*CommonRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonRsp)
	err := c.cc.Invoke(ctx, TableWService_GetTableRowByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableWServiceClient) DoExportTable(ctx context.Context, in *GetTableRowsReq, opts ...grpc.CallOption) (*CommonRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonRsp)
	err := c.cc.Invoke(ctx, TableWService_DoExportTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableWServiceClient) GetTableColumnOptions(ctx context.Context, in *GetTableColumnOptionsReq, opts ...grpc.CallOption) (*CommonRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonRsp)
	err := c.cc.Invoke(ctx, TableWService_GetTableColumnOptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableWServiceClient) GetTableRowsLite(ctx context.Context, in *GetTableRowsLiteReq, opts ...grpc.CallOption) (*CommonRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonRsp)
	err := c.cc.Invoke(ctx, TableWService_GetTableRowsLite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableWServiceClient) GetOptions(ctx context.Context, in *GetOptionsReq, opts ...grpc.CallOption) (*CommonRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonRsp)
	err := c.cc.Invoke(ctx, TableWService_GetOptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableWServiceClient) DoRowFormAction(ctx context.Context, in *DoRowFormActionReq, opts ...grpc.CallOption) (*CommonRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonRsp)
	err := c.cc.Invoke(ctx, TableWService_DoRowFormAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableWServiceClient) DeleteRows(ctx context.Context, in *DeleteRowsReq, opts ...grpc.CallOption) (*CommonRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonRsp)
	err := c.cc.Invoke(ctx, TableWService_DeleteRows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TableWServiceServer is the server API for TableWService service.
// All implementations should embed UnimplementedTableWServiceServer
// for forward compatibility.
//
// TableWService 表格服务
// 每个子系统都可能提供该服务 /cap.TableWService，并统一通过EAP的端口暴露
// 前端可使用http header["Subsystem"]或者["Referer"]来指定子系统
// 例如访问[mts]下的表格服务，可以如下设置：
//
//	示例1: HTTP Header["Subsystem"] = "/mts"
//	示例2: HTTP Header["Referer"] = "/mts/...."
//
// 注意：上线系统中referer由浏览器自动设置，无需手动设置，调试时可使用Subsystem
// Header
type TableWServiceServer interface {
	// 表
	// GetTableInfo 获取表信息
	GetTableInfo(context.Context, *GetTableInfoReq) (*CommonRsp, error)
	// 模板
	// GetTableTemplates 获取表模板信息
	GetTableTemplates(context.Context, *GetTableTemplatesReq) (*CommonRsp, error)
	// CreateTableTemplate 创建模板
	CreateTableTemplate(context.Context, *CreateTableTemplateReq) (*CommonRsp, error)
	// DeleteTableTemplate 删除模板
	DeleteTableTemplate(context.Context, *DeleteTableTemplateReq) (*CommonRsp, error)
	// UpdateTableTemplate 更新模板
	UpdateTableTemplate(context.Context, *CreateTableTemplateReq) (*CommonRsp, error)
	// 数据
	// GetTableColumns 获取表列
	GetTableColumns(context.Context, *GetTableColumnsReq) (*CommonRsp, error)
	// GetTableRows 获取表行
	GetTableRows(context.Context, *GetTableRowsReq) (*CommonRsp, error)
	// GetTableRowByID 精确获取一行
	GetTableRowByID(context.Context, *GetTableRowByIDReq) (*CommonRsp, error)
	// DoExportTable 导出表
	DoExportTable(context.Context, *GetTableRowsReq) (*CommonRsp, error)
	// GetTableColumnOptions 获取列选项列表（仅ValueType = VT_OPTION时可获取）
	GetTableColumnOptions(context.Context, *GetTableColumnOptionsReq) (*CommonRsp, error)
	// GetTableRowsLite 简单版获取行列表接口
	GetTableRowsLite(context.Context, *GetTableRowsLiteReq) (*CommonRsp, error)
	// GetOptions 根据Option ID获取
	GetOptions(context.Context, *GetOptionsReq) (*CommonRsp, error)
	// 执行表单操作
	DoRowFormAction(context.Context, *DoRowFormActionReq) (*CommonRsp, error)
	// 执行表单操作
	DeleteRows(context.Context, *DeleteRowsReq) (*CommonRsp, error)
}

// UnimplementedTableWServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTableWServiceServer struct{}

func (UnimplementedTableWServiceServer) GetTableInfo(context.Context, *GetTableInfoReq) (*CommonRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTableInfo not implemented")
}
func (UnimplementedTableWServiceServer) GetTableTemplates(context.Context, *GetTableTemplatesReq) (*CommonRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTableTemplates not implemented")
}
func (UnimplementedTableWServiceServer) CreateTableTemplate(context.Context, *CreateTableTemplateReq) (*CommonRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTableTemplate not implemented")
}
func (UnimplementedTableWServiceServer) DeleteTableTemplate(context.Context, *DeleteTableTemplateReq) (*CommonRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTableTemplate not implemented")
}
func (UnimplementedTableWServiceServer) UpdateTableTemplate(context.Context, *CreateTableTemplateReq) (*CommonRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTableTemplate not implemented")
}
func (UnimplementedTableWServiceServer) GetTableColumns(context.Context, *GetTableColumnsReq) (*CommonRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTableColumns not implemented")
}
func (UnimplementedTableWServiceServer) GetTableRows(context.Context, *GetTableRowsReq) (*CommonRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTableRows not implemented")
}
func (UnimplementedTableWServiceServer) GetTableRowByID(context.Context, *GetTableRowByIDReq) (*CommonRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTableRowByID not implemented")
}
func (UnimplementedTableWServiceServer) DoExportTable(context.Context, *GetTableRowsReq) (*CommonRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoExportTable not implemented")
}
func (UnimplementedTableWServiceServer) GetTableColumnOptions(context.Context, *GetTableColumnOptionsReq) (*CommonRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTableColumnOptions not implemented")
}
func (UnimplementedTableWServiceServer) GetTableRowsLite(context.Context, *GetTableRowsLiteReq) (*CommonRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTableRowsLite not implemented")
}
func (UnimplementedTableWServiceServer) GetOptions(context.Context, *GetOptionsReq) (*CommonRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOptions not implemented")
}
func (UnimplementedTableWServiceServer) DoRowFormAction(context.Context, *DoRowFormActionReq) (*CommonRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoRowFormAction not implemented")
}
func (UnimplementedTableWServiceServer) DeleteRows(context.Context, *DeleteRowsReq) (*CommonRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRows not implemented")
}
func (UnimplementedTableWServiceServer) testEmbeddedByValue() {}

// UnsafeTableWServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TableWServiceServer will
// result in compilation errors.
type UnsafeTableWServiceServer interface {
	mustEmbedUnimplementedTableWServiceServer()
}

func RegisterTableWServiceServer(s grpc.ServiceRegistrar, srv TableWServiceServer) {
	// If the following call pancis, it indicates UnimplementedTableWServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TableWService_ServiceDesc, srv)
}

func _TableWService_GetTableInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTableInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableWServiceServer).GetTableInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableWService_GetTableInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableWServiceServer).GetTableInfo(ctx, req.(*GetTableInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableWService_GetTableTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTableTemplatesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableWServiceServer).GetTableTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableWService_GetTableTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableWServiceServer).GetTableTemplates(ctx, req.(*GetTableTemplatesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableWService_CreateTableTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTableTemplateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableWServiceServer).CreateTableTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableWService_CreateTableTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableWServiceServer).CreateTableTemplate(ctx, req.(*CreateTableTemplateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableWService_DeleteTableTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTableTemplateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableWServiceServer).DeleteTableTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableWService_DeleteTableTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableWServiceServer).DeleteTableTemplate(ctx, req.(*DeleteTableTemplateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableWService_UpdateTableTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTableTemplateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableWServiceServer).UpdateTableTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableWService_UpdateTableTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableWServiceServer).UpdateTableTemplate(ctx, req.(*CreateTableTemplateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableWService_GetTableColumns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTableColumnsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableWServiceServer).GetTableColumns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableWService_GetTableColumns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableWServiceServer).GetTableColumns(ctx, req.(*GetTableColumnsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableWService_GetTableRows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTableRowsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableWServiceServer).GetTableRows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableWService_GetTableRows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableWServiceServer).GetTableRows(ctx, req.(*GetTableRowsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableWService_GetTableRowByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTableRowByIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableWServiceServer).GetTableRowByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableWService_GetTableRowByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableWServiceServer).GetTableRowByID(ctx, req.(*GetTableRowByIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableWService_DoExportTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTableRowsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableWServiceServer).DoExportTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableWService_DoExportTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableWServiceServer).DoExportTable(ctx, req.(*GetTableRowsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableWService_GetTableColumnOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTableColumnOptionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableWServiceServer).GetTableColumnOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableWService_GetTableColumnOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableWServiceServer).GetTableColumnOptions(ctx, req.(*GetTableColumnOptionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableWService_GetTableRowsLite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTableRowsLiteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableWServiceServer).GetTableRowsLite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableWService_GetTableRowsLite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableWServiceServer).GetTableRowsLite(ctx, req.(*GetTableRowsLiteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableWService_GetOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOptionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableWServiceServer).GetOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableWService_GetOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableWServiceServer).GetOptions(ctx, req.(*GetOptionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableWService_DoRowFormAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoRowFormActionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableWServiceServer).DoRowFormAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableWService_DoRowFormAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableWServiceServer).DoRowFormAction(ctx, req.(*DoRowFormActionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableWService_DeleteRows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRowsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableWServiceServer).DeleteRows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableWService_DeleteRows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableWServiceServer).DeleteRows(ctx, req.(*DeleteRowsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TableWService_ServiceDesc is the grpc.ServiceDesc for TableWService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TableWService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cap.TableWService",
	HandlerType: (*TableWServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTableInfo",
			Handler:    _TableWService_GetTableInfo_Handler,
		},
		{
			MethodName: "GetTableTemplates",
			Handler:    _TableWService_GetTableTemplates_Handler,
		},
		{
			MethodName: "CreateTableTemplate",
			Handler:    _TableWService_CreateTableTemplate_Handler,
		},
		{
			MethodName: "DeleteTableTemplate",
			Handler:    _TableWService_DeleteTableTemplate_Handler,
		},
		{
			MethodName: "UpdateTableTemplate",
			Handler:    _TableWService_UpdateTableTemplate_Handler,
		},
		{
			MethodName: "GetTableColumns",
			Handler:    _TableWService_GetTableColumns_Handler,
		},
		{
			MethodName: "GetTableRows",
			Handler:    _TableWService_GetTableRows_Handler,
		},
		{
			MethodName: "GetTableRowByID",
			Handler:    _TableWService_GetTableRowByID_Handler,
		},
		{
			MethodName: "DoExportTable",
			Handler:    _TableWService_DoExportTable_Handler,
		},
		{
			MethodName: "GetTableColumnOptions",
			Handler:    _TableWService_GetTableColumnOptions_Handler,
		},
		{
			MethodName: "GetTableRowsLite",
			Handler:    _TableWService_GetTableRowsLite_Handler,
		},
		{
			MethodName: "GetOptions",
			Handler:    _TableWService_GetOptions_Handler,
		},
		{
			MethodName: "DoRowFormAction",
			Handler:    _TableWService_DoRowFormAction_Handler,
		},
		{
			MethodName: "DeleteRows",
			Handler:    _TableWService_DeleteRows_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "table_wservice.proto",
}
