// Code generated by protoc-gen-go. DO NOT EDIT.
// source: enum.proto

package extension

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

var E_FormName = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1500,
	Name:          "extension.form_name",
	Tag:           "bytes,1500,opt,name=form_name",
	Filename:      "enum.proto",
}

var E_OrderType = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1501,
	Name:          "extension.order_type",
	Tag:           "bytes,1501,opt,name=order_type",
	Filename:      "enum.proto",
}

var E_DeliveryNoticeType = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1502,
	Name:          "extension.delivery_notice_type",
	Tag:           "bytes,1502,opt,name=delivery_notice_type",
	Filename:      "enum.proto",
}

var E_ReturnNoticeType = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1503,
	Name:          "extension.return_notice_type",
	Tag:           "bytes,1503,opt,name=return_notice_type",
	Filename:      "enum.proto",
}

var E_MpType = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1504,
	Name:          "extension.mp_type",
	Tag:           "bytes,1504,opt,name=mp_type",
	Filename:      "enum.proto",
}

var E_IssuemtrNoticeType = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1505,
	Name:          "extension.issuemtr_notice_type",
	Tag:           "bytes,1505,opt,name=issuemtr_notice_type",
	Filename:      "enum.proto",
}

var E_OrderTypeName = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1506,
	Name:          "extension.order_type_name",
	Tag:           "bytes,1506,opt,name=order_type_name",
	Filename:      "enum.proto",
}

var E_DeliveryNoticeTypeName = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1507,
	Name:          "extension.delivery_notice_type_name",
	Tag:           "bytes,1507,opt,name=delivery_notice_type_name",
	Filename:      "enum.proto",
}

var E_ReturnNoticeTypeName = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1508,
	Name:          "extension.return_notice_type_name",
	Tag:           "bytes,1508,opt,name=return_notice_type_name",
	Filename:      "enum.proto",
}

var E_MpTypeName = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1509,
	Name:          "extension.mp_type_name",
	Tag:           "bytes,1509,opt,name=mp_type_name",
	Filename:      "enum.proto",
}

var E_IssuemtrNoticeTypeName = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1510,
	Name:          "extension.issuemtr_notice_type_name",
	Tag:           "bytes,1510,opt,name=issuemtr_notice_type_name",
	Filename:      "enum.proto",
}

var E_ResultType = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1511,
	Name:          "extension.result_type",
	Tag:           "bytes,1511,opt,name=result_type",
	Filename:      "enum.proto",
}

var E_OperationType = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1512,
	Name:          "extension.operation_type",
	Tag:           "bytes,1512,opt,name=operation_type",
	Filename:      "enum.proto",
}

var E_CloseStatus = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1513,
	Name:          "extension.close_status",
	Tag:           "bytes,1513,opt,name=close_status",
	Filename:      "enum.proto",
}

var E_CancelStatus = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1514,
	Name:          "extension.cancel_status",
	Tag:           "bytes,1514,opt,name=cancel_status",
	Filename:      "enum.proto",
}

var E_CloseStatusName = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1515,
	Name:          "extension.close_status_name",
	Tag:           "bytes,1515,opt,name=close_status_name",
	Filename:      "enum.proto",
}

var E_CancelStatusName = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1516,
	Name:          "extension.cancel_status_name",
	Tag:           "bytes,1516,opt,name=cancel_status_name",
	Filename:      "enum.proto",
}

var E_SectionTypeName = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1517,
	Name:          "extension.section_type_name",
	Tag:           "bytes,1517,opt,name=section_type_name",
	Filename:      "enum.proto",
}

var E_DocumentStatus = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1518,
	Name:          "extension.document_status",
	Tag:           "bytes,1518,opt,name=document_status",
	Filename:      "enum.proto",
}

var E_DocumentStatusName = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1519,
	Name:          "extension.document_status_name",
	Tag:           "bytes,1519,opt,name=document_status_name",
	Filename:      "enum.proto",
}

var E_OrderTransform = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1520,
	Name:          "extension.order_transform",
	Tag:           "bytes,1520,opt,name=order_transform",
	Filename:      "enum.proto",
}

var E_CommonName = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1521,
	Name:          "extension.common_name",
	Tag:           "bytes,1521,opt,name=common_name",
	Filename:      "enum.proto",
}

var E_PickMtrlType = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1522,
	Name:          "extension.pick_mtrl_type",
	Tag:           "bytes,1522,opt,name=pick_mtrl_type",
	Filename:      "enum.proto",
}

var E_PickMtrlTypeName = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1523,
	Name:          "extension.pick_mtrl_type_name",
	Tag:           "bytes,1523,opt,name=pick_mtrl_type_name",
	Filename:      "enum.proto",
}

var E_OrderSubType = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1524,
	Name:          "extension.order_sub_type",
	Tag:           "bytes,1524,opt,name=order_sub_type",
	Filename:      "enum.proto",
}

var E_OutStockName = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1525,
	Name:          "extension.out_stock_name",
	Tag:           "bytes,1525,opt,name=out_stock_name",
	Filename:      "enum.proto",
}

var E_ReturnMaterialStockInName = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1526,
	Name:          "extension.return_material_stock_in_name",
	Tag:           "bytes,1526,opt,name=return_material_stock_in_name",
	Filename:      "enum.proto",
}

var E_ReturnStockName = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1527,
	Name:          "extension.return_stock_name",
	Tag:           "bytes,1527,opt,name=return_stock_name",
	Filename:      "enum.proto",
}

var E_MiscellaneousStockInName = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1528,
	Name:          "extension.miscellaneous_stock_in_name",
	Tag:           "bytes,1528,opt,name=miscellaneous_stock_in_name",
	Filename:      "enum.proto",
}

var E_OptionName = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         3456,
	Name:          "extension.option_name",
	Tag:           "bytes,3456,opt,name=option_name",
	Filename:      "enum.proto",
}

var E_RfcValue = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         3457,
	Name:          "extension.rfc_value",
	Tag:           "bytes,3457,opt,name=rfc_value",
	Filename:      "enum.proto",
}

func init() {
	proto.RegisterExtension(E_FormName)
	proto.RegisterExtension(E_OrderType)
	proto.RegisterExtension(E_DeliveryNoticeType)
	proto.RegisterExtension(E_ReturnNoticeType)
	proto.RegisterExtension(E_MpType)
	proto.RegisterExtension(E_IssuemtrNoticeType)
	proto.RegisterExtension(E_OrderTypeName)
	proto.RegisterExtension(E_DeliveryNoticeTypeName)
	proto.RegisterExtension(E_ReturnNoticeTypeName)
	proto.RegisterExtension(E_MpTypeName)
	proto.RegisterExtension(E_IssuemtrNoticeTypeName)
	proto.RegisterExtension(E_ResultType)
	proto.RegisterExtension(E_OperationType)
	proto.RegisterExtension(E_CloseStatus)
	proto.RegisterExtension(E_CancelStatus)
	proto.RegisterExtension(E_CloseStatusName)
	proto.RegisterExtension(E_CancelStatusName)
	proto.RegisterExtension(E_SectionTypeName)
	proto.RegisterExtension(E_DocumentStatus)
	proto.RegisterExtension(E_DocumentStatusName)
	proto.RegisterExtension(E_OrderTransform)
	proto.RegisterExtension(E_CommonName)
	proto.RegisterExtension(E_PickMtrlType)
	proto.RegisterExtension(E_PickMtrlTypeName)
	proto.RegisterExtension(E_OrderSubType)
	proto.RegisterExtension(E_OutStockName)
	proto.RegisterExtension(E_ReturnMaterialStockInName)
	proto.RegisterExtension(E_ReturnStockName)
	proto.RegisterExtension(E_MiscellaneousStockInName)
	proto.RegisterExtension(E_OptionName)
	proto.RegisterExtension(E_RfcValue)
}

func init() { proto.RegisterFile("enum.proto", fileDescriptor_13a9f1b5947140c8) }

var fileDescriptor_13a9f1b5947140c8 = []byte{
	// 703 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x96, 0xc9, 0x6f, 0x13, 0x4d,
	0x10, 0xc5, 0xf5, 0x5d, 0xf2, 0xc5, 0xe5, 0x2c, 0xc4, 0x44, 0x90, 0x10, 0x21, 0x85, 0x1b, 0x17,
	0xec, 0x03, 0x37, 0xe7, 0x10, 0x91, 0x45, 0x10, 0x50, 0x4c, 0x20, 0x11, 0x12, 0x48, 0xc8, 0x1a,
	0xb7, 0xcb, 0xce, 0x28, 0xd3, 0xdd, 0xa3, 0x5e, 0x02, 0xbe, 0xc1, 0xff, 0xc9, 0xbe, 0xef, 0xfb,
	0x76, 0x44, 0xd3, 0xd5, 0xed, 0xd8, 0x24, 0x87, 0xf6, 0xcd, 0xf2, 0xd4, 0xfb, 0xcd, 0xeb, 0x7a,
	0x5d, 0xa5, 0x01, 0x40, 0x61, 0x79, 0x35, 0x57, 0xd2, 0xc8, 0x4a, 0x09, 0xef, 0x1a, 0x14, 0x3a,
	0x95, 0xe2, 0xd4, 0x62, 0x57, 0xca, 0x6e, 0x86, 0x35, 0xf7, 0xa0, 0x65, 0x3b, 0xb5, 0x36, 0x6a,
	0xa6, 0xd2, 0xdc, 0x48, 0x45, 0xc5, 0xf5, 0x65, 0x28, 0x75, 0xa4, 0xe2, 0x4d, 0x91, 0x70, 0xac,
	0x9c, 0xa9, 0x52, 0x7d, 0x35, 0xd4, 0x57, 0xd7, 0x85, 0xe5, 0x37, 0x92, 0xcc, 0xe2, 0xd5, 0xdc,
	0xa4, 0x52, 0xe8, 0xb9, 0x07, 0xe5, 0xc5, 0xff, 0xce, 0x96, 0xae, 0x8f, 0x17, 0xa2, 0x46, 0xc2,
	0xb1, 0x7e, 0x01, 0x40, 0xaa, 0x36, 0xaa, 0xa6, 0xe9, 0xe5, 0x51, 0x84, 0x87, 0x44, 0x28, 0x39,
	0xd5, 0x4e, 0x2f, 0xc7, 0xfa, 0x0e, 0xcc, 0xb6, 0x31, 0x4b, 0xf7, 0x51, 0xf5, 0x9a, 0x42, 0x9a,
	0x94, 0x61, 0x34, 0xec, 0x11, 0xc1, 0x2a, 0x41, 0xdf, 0x70, 0x72, 0x47, 0xdd, 0x82, 0x8a, 0x42,
	0x63, 0x95, 0x18, 0x95, 0xf9, 0x98, 0x98, 0xc7, 0x48, 0x3d, 0x40, 0x5c, 0x82, 0xff, 0x79, 0x1e,
	0x8d, 0x79, 0x42, 0x98, 0x31, 0x9e, 0x87, 0x43, 0xa6, 0x5a, 0x5b, 0xe4, 0x46, 0x8d, 0x6a, 0xe8,
	0xa9, 0x3f, 0x64, 0xd0, 0x0f, 0x58, 0xba, 0x0c, 0xd3, 0x07, 0xdd, 0x8f, 0x0e, 0xf1, 0x19, 0x01,
	0x27, 0xfb, 0x11, 0xb8, 0x24, 0x6f, 0xc3, 0xfc, 0x51, 0x31, 0x44, 0x53, 0x9f, 0x13, 0xf5, 0xc4,
	0xe1, 0x2c, 0x1c, 0xfe, 0x26, 0x9c, 0x3c, 0x9c, 0x47, 0x34, 0xfc, 0x05, 0xc1, 0x67, 0xff, 0x0d,
	0xc5, 0xa1, 0xd7, 0x60, 0xc2, 0x07, 0x13, 0xcd, 0x7b, 0x49, 0x3c, 0xa0, 0x74, 0xc2, 0xf9, 0x8f,
	0x4a, 0x28, 0x1a, 0xf9, 0xca, 0x9f, 0xff, 0x70, 0x4c, 0x0e, 0xbf, 0x0a, 0x65, 0x85, 0xda, 0x66,
	0x26, 0x3a, 0xf7, 0xd7, 0xde, 0x23, 0xc9, 0x5c, 0xde, 0x1b, 0x30, 0x25, 0x73, 0x54, 0x49, 0x51,
	0x10, 0xcd, 0x79, 0x13, 0xe2, 0x0e, 0x4a, 0x87, 0x5a, 0x87, 0x09, 0x96, 0x49, 0x8d, 0x4d, 0x6d,
	0x12, 0x63, 0x75, 0x0c, 0xe8, 0x2d, 0x81, 0xca, 0x4e, 0xb7, 0xed, 0x64, 0xf5, 0x8b, 0x30, 0xc9,
	0x12, 0xc1, 0x30, 0x1b, 0x81, 0xf3, 0x8e, 0x38, 0x13, 0x24, 0xf4, 0xa0, 0x06, 0xcc, 0x0c, 0xfa,
	0x89, 0x6e, 0xfb, 0x7b, 0x82, 0x4d, 0x0f, 0x98, 0x72, 0xfd, 0xde, 0x82, 0xca, 0x90, 0xb1, 0x68,
	0xe0, 0x07, 0x3f, 0xff, 0x83, 0xee, 0x1c, 0xb1, 0x01, 0x33, 0x1a, 0x59, 0xbf, 0xf5, 0xd1, 0xc0,
	0x8f, 0xde, 0xa1, 0x17, 0xf7, 0x6f, 0xc4, 0x15, 0x98, 0x6e, 0x4b, 0x66, 0x39, 0x0a, 0x33, 0x42,
	0xf3, 0x3e, 0x11, 0x6d, 0x2a, 0x48, 0x7d, 0xfb, 0x8a, 0x25, 0x3a, 0x0c, 0x8b, 0xf6, 0xf7, 0x39,
	0x2c, 0xd1, 0x21, 0x62, 0xb0, 0xe8, 0xf7, 0x8b, 0x4a, 0x84, 0x2e, 0x96, 0x7e, 0x0c, 0xf0, 0x8b,
	0xb7, 0x48, 0xfb, 0x25, 0x28, 0x8b, 0x09, 0x60, 0x92, 0x73, 0x29, 0xa2, 0x9d, 0x7d, 0xf5, 0x13,
	0x40, 0x32, 0xe7, 0xe8, 0x12, 0x4c, 0xe5, 0x29, 0xdb, 0x6b, 0x72, 0xa3, 0xb2, 0xe8, 0x09, 0xf8,
	0xe6, 0x2f, 0x5c, 0xa1, 0xdc, 0x34, 0x2a, 0x73, 0x03, 0x70, 0x0d, 0x8e, 0x0f, 0x93, 0xa2, 0x6d,
	0x7d, 0xf7, 0x37, 0x64, 0x10, 0x17, 0xcc, 0x51, 0xbb, 0xb4, 0x6d, 0x45, 0x9b, 0xfb, 0xe1, 0xcd,
	0x39, 0xe5, 0xb6, 0x6d, 0x39, 0x73, 0x05, 0xc9, 0x16, 0x49, 0x4a, 0xb6, 0x17, 0xed, 0xeb, 0x67,
	0x20, 0x59, 0xb3, 0x5d, 0x08, 0x9d, 0xa7, 0x36, 0x9c, 0xf6, 0x7b, 0x97, 0x27, 0x06, 0x55, 0x9a,
	0x64, 0x9e, 0x9a, 0xc6, 0xe7, 0xf0, 0x8b, 0xc0, 0xf3, 0x04, 0xda, 0xf4, 0x1c, 0xf7, 0x8e, 0x0d,
	0x11, 0x66, 0xc3, 0xbf, 0x65, 0x34, 0xcb, 0xbf, 0xfd, 0x6c, 0x90, 0xf8, 0xc0, 0x75, 0x02, 0x0b,
	0x3c, 0xd5, 0x0c, 0xb3, 0x2c, 0x11, 0x28, 0xad, 0x1e, 0xdd, 0xf3, 0x1f, 0x22, 0xcf, 0x0d, 0x61,
	0x06, 0x2d, 0xaf, 0x42, 0x59, 0xba, 0xda, 0x68, 0xe4, 0xbd, 0x05, 0xba, 0x8e, 0x24, 0x73, 0x90,
	0x65, 0x28, 0xa9, 0x0e, 0x6b, 0xee, 0x17, 0x65, 0x31, 0x88, 0xfb, 0x84, 0x18, 0x57, 0x1d, 0xe6,
	0xfe, 0x5f, 0x59, 0xbb, 0xb5, 0xd2, 0x4d, 0x4d, 0x96, 0xb4, 0xaa, 0x79, 0x2a, 0x0c, 0xb2, 0x5d,
	0x5d, 0x65, 0x92, 0xd7, 0x70, 0xb7, 0x86, 0x02, 0x55, 0xb7, 0x77, 0xae, 0x95, 0xb0, 0x3d, 0x14,
	0xed, 0xda, 0x1d, 0x6c, 0x39, 0x6c, 0xad, 0xff, 0x79, 0xb7, 0xd4, 0xff, 0xd5, 0x1a, 0x73, 0x8f,
	0xce, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x11, 0x5e, 0xc4, 0xa4, 0x08, 0x0a, 0x00, 0x00,
}
