// generated by cap, DO NOT EDIT.
package test

import (
	"fmt"
	i18n "gitlab.pintechs.com/eh/energy-backend/cap/msg/i18n"
	language "golang.org/x/text/language"
)

// supported languages:
var Lang_zhCN = language.Make("zh-CN")
var Lang_enUS = language.Make("en-US")
var languageMatcher = language.NewMatcher([]language.Tag{Lang_zhCN, Lang_enUS})

// language matcher
func MatchLang(lang string) (tag language.Tag, err error) {
	langTag := language.Make(lang)
	matchedTag, _, c := languageMatcher.Match(langTag)
	if c < language.High {
		return matchedTag, fmt.Errorf("no confidence language matched")
	}
	return matchedTag, nil
}

// language id definition:
// ERR_1 用户名或密码错误
const ERR_1 = i18n.TrID("v_ERR_1")

// ERR_2 测试
const ERR_2 = i18n.TrID("v_ERR_2")
